version: '3.3'
services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: agamova/foodgram:latest
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    command: bash -c "python3 manage.py makemigrations
             && python3 manage.py migrate
             && python3 manage.py collectstatic --noinput
             && python3 manage.py loader_csv
             && python3 manage.py superuser_create
             && gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: agamova/frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs:/usr/share/nginx/html/api/docs
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml

    depends_on:
      - web
      - frontend

volumes:

  postgres_data:
  static_value:
  media_value:
