# Generated by Django 2.2.16 on 2021-12-10 12:35

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20211209_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[recipes.validators.is_convertible_to_color], verbose_name='Цветовой HEX-код'),
        ),
    ]
