# Generated by Django 2.2.16 on 2021-12-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211216_0853'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='it is impossible to subscribe to yourself',
        ),
    ]
