# Generated by Django 2.2.16 on 2021-12-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211216_0857'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'user'), name='impossible subscribe to yourself'),
        ),
    ]
