# Generated by Django 2.2.16 on 2021-12-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211216_0901'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='impossible subscribe to yourself',
        ),
    ]
